services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser
      npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true